---
engines:
  rubocop:
    exclude_paths:
      - ".bundle/**"
      - "spec/**/*"
      - "benchmarks/**/*"
      - "**.min.js"
      - "tests/**/*"
      - "node_modules/**/*"
    base_sub_dir: "./"
  duplication:
    exclude_paths:
      - ".bundle/**"
      - "spec/**/*"
      - "benchmarks/**/*"
      - "**.min.js"
      - "tests/**/*"
      - "node_modules/**/*"
    config:
      languages:
        - "javascript"
languages:
  css:
    extensions:
      - "-css.resource"
exclude_paths:
  - ".bundle/**"
  - "spec/**/*"
  - "benchmarks/**/*"
  - "**.min.js"
  - "tests/**/*"
  - "node_modules/**/*"